version: '3'
services:

 db:
  image: mysql
  hostname: mysql
  container_name: mysql
  privileged: true
  volumes:
   - mysql:/var/lib/mysql/
  expose:
   - "3306"
  environment:
   - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  networks:
   mynet:
    ipv4_address: 192.168.0.2

 powerdns:
  image: powerdns:1.0.0
  hostname: powerdns
  container_name: powerdns
  privileged: true
  volumes:
   - powerdns:/var/www/html/
  expose:
   - "53"
   - "80"
  ports:
   - "53:53/udp"
   - "53:53"
   - "80:80"
  links:
   - "db:mysql"
  networks:
   mynet:
    ipv4_address: 192.168.0.3

 
volumes:
 mysql:
  external:
   name: mysql
 powerdns:
  external:
   name: powerdns

networks:
 mynet:
  driver: bridge
  ipam:
   config:
    - subnet: 192.168.0.0/29
